# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18OFhTd3UX-1t3SRFMAh3PCV1L-4gOXj-
"""

import numpy as np
from scipy.optimize import minimize

# Define constants
g = 9.81
mu = 0.8
track_length = 1000
delta_theta_max = 1.0
r_max_track = 20

# Define the objective function (minimize time with penalty for large radius - for ease)
def objective_function(x):
    return track_length / x[1] + x[0] / x[1]**2

# Define the constraint functions
def friction_constraint(x):
    return (x[1]**2 / x[0]) - mu * g

def turning_angle_constraint(x):
    return delta_theta_max - np.arctan(1 / x[0])

def track_radius_constraint(x):
    return r_max_track - x[0]

def engine_power_constraint(x):
    max_velocity = 120  # m/s
    return max_velocity - x[1]

# Initial guess
x0 = np.array([15, 90])


bounds = [(10, 20), (70, 100)]  # bounds for radius and velocity

# Define all constraints
constraints = [
    {'type': 'ineq', 'fun': friction_constraint},
    {'type': 'ineq', 'fun': turning_angle_constraint},
    {'type': 'ineq', 'fun': track_radius_constraint},
    {'type': 'ineq', 'fun': engine_power_constraint},
]

# Solve the optimization problem
result = minimize(objective_function, x0, method='SLSQP', bounds=bounds, constraints=constraints)

# Print the optimal solution
print("Optimal solution:")
print("Radius:", result.x[0])
print("Velocity:", result.x[1])
print("Optimal objective value (time):", result.fun)

# Calculate additional performance metrics (assuming constant acceleration)
acceleration = (result.x[1]**2) / result.x[0] - mu * g
mass = 1000
cornering_force = mass * acceleration

print("Maximum lateral acceleration:", cornering_force / (result.x[0] * mass))