# -*- coding: utf-8 -*-
"""nlpv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvyGB-qp6oHpRFxtp_ecvAWbPNF7dKF9
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# Simulation Constants
G = 9.81
MU_BASE = 1.2        # Base friction coefficient
A_MAX = 5.0          # Max engine acceleration (m/s^2)
DECEL_MAX = 9.0      # Max braking deceleration (m/s^2)
TRACK_WIDTH = 12.0   # Total width of the track in meters

class RacingLineOptimizer:
    def __init__(self, track_coords, track_width=TRACK_WIDTH):
        self.centerline = track_coords
        self.width = track_width
        self.n_points = len(track_coords)

        # Geometry Pre-calculations
        self.diffs = np.diff(self.centerline, axis=0, append=[self.centerline[0]])
        self.segment_lengths = np.linalg.norm(self.diffs, axis=1)

        # Calculate Unit Normals for the track boundaries
        self.normals = np.zeros_like(self.centerline)
        self.normals[:, 0] = -self.diffs[:, 1]
        self.normals[:, 1] = self.diffs[:, 0]
        self.normals /= np.linalg.norm(self.normals, axis=1)[:, np.newaxis]

    def _get_friction_map(self, coords):
        dist_from_center = np.linalg.norm(coords - self.centerline, axis=1)
        friction = np.full(len(coords), MU_BASE)
        marbles_threshold = self.width * 0.4
        friction[dist_from_center > marbles_threshold] *= 0.7
        return friction

    def _calculate_curvature(self, coords):
        dx = np.gradient(coords[:, 0])
        dy = np.gradient(coords[:, 1])
        ddx = np.gradient(dx)
        ddy = np.gradient(dy)
        curvature = np.abs(dx * ddy - dy * ddx) / (dx**2 + dy**2 + 1e-6)**1.5
        return curvature

    def _apply_longitudinal_limits(self, coords, v_max_lat):
        v_profile = np.copy(v_max_lat)
        ds = np.linalg.norm(np.diff(coords, axis=0, append=[coords[0]]), axis=1)

        for i in range(len(v_profile) - 1):
            v_reach = np.sqrt(v_profile[i]**2 + 2 * A_MAX * ds[i])
            v_profile[i+1] = min(v_profile[i+1], v_reach)

        for i in range(len(v_profile) - 1, 0, -1):
            v_brake = np.sqrt(v_profile[i]**2 + 2 * DECEL_MAX * ds[i-1])
            v_profile[i-1] = min(v_profile[i-1], v_brake)

        return v_profile

    def calculate_lap_time(self, alphas):
        coords = self.centerline + (alphas[:, np.newaxis] * self.normals)
        curvature = self._calculate_curvature(coords)
        friction = self._get_friction_map(coords)

        v_max_lat = np.sqrt(friction * G / (curvature + 1e-6))
        v_final = self._apply_longitudinal_limits(coords, v_max_lat)

        ds = np.linalg.norm(np.diff(coords, axis=0, append=[coords[0]]), axis=1)
        lap_time = np.sum(ds / (v_final + 1e-6))
        return lap_time, v_final, coords

    def solve(self):
        initial_guess = np.zeros(self.n_points)
        limit = self.width / 2.0
        bounds = [(-limit, limit) for _ in range(self.n_points)]

        print("Running SLSQP Optimizer...")
        res = minimize(lambda x: self.calculate_lap_time(x)[0],
                       initial_guess, method='SLSQP',
                       bounds=bounds, options={'ftol': 1e-4, 'maxiter': 50})

        final_time, v_profile, opt_coords = self.calculate_lap_time(res.x)
        return opt_coords, v_profile, final_time

t = np.linspace(0, 1, 100)
centerline = np.column_stack([200 * t, 60 * np.sin(2 * np.pi * t)])

opt = RacingLineOptimizer(centerline)
initial_time, _, _ = opt.calculate_lap_time(np.zeros(len(centerline)))
optimal_path, v_profile, final_time = opt.solve()

print("\n" + "="*30)
print("   OPTIMIZATION RESULTS")
print("="*30)
print(f"Initial Lap Time:   {initial_time:.3f} s")
print(f"Optimized Lap Time: {final_time:.3f} s")
print(f"Time Improvement:   {initial_time - final_time:.3f} s ({(1 - final_time/initial_time)*100:.1f}%)")
print("-" * 30)
print(f"Max Velocity:       {np.max(v_profile):.2f} m/s ({np.max(v_profile)*3.6:.1f} km/h)")
print(f"Min Velocity:       {np.min(v_profile):.2f} m/s ({np.min(v_profile)*3.6:.1f} km/h)")
print(f"Average Velocity:   {np.mean(v_profile):.2f} m/s")
print("="*30)

plt.figure(figsize=(15, 6))
inner = opt.centerline - (opt.width/2 * opt.normals)
outer = opt.centerline + (opt.width/2 * opt.normals)
plt.plot(inner[:,0], inner[:,1], 'k', alpha=0.4)
plt.plot(outer[:,0], outer[:,1], 'k', alpha=0.4)
plt.fill(np.append(inner[:,0], outer[::-1,0]), np.append(inner[:,1], outer[::-1,1]), 'lightgray', alpha=0.2)

sc = plt.scatter(optimal_path[:,0], optimal_path[:,1], c=v_profile, cmap='turbo', s=20)
plt.colorbar(sc, label='Velocity (m/s)')
plt.title("NLP Racing Line: Velocity Profile & Trajectory")
plt.axis('equal')
plt.show()