# -*- coding: utf-8 -*-
"""psov2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3WPcG0zsi2WT3qZx9bj6HRPz8jj2VHg
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from scipy.interpolate import CubicSpline
from IPython.display import HTML

G, MU = 9.81, 1.35
A_MAX, DECEL_MAX = 7.5, 10.5
TRACK_WIDTH = 15.0

N_PARTICLES = 60
N_ITERATIONS = 150
N_NODES = 20

# Track Generation
t = np.linspace(0, 2*np.pi, 250, endpoint=False)
x = 140 * np.cos(t) + 40 * np.sin(3*t)
y = 100 * np.sin(t) + 30 * np.cos(2*t)
centerline = np.column_stack([x, y])

# Compute Normals
diffs = np.roll(centerline, -1, axis=0) - centerline
normals = np.zeros_like(centerline)
normals[:, 0] = -diffs[:, 1]; normals[:, 1] = diffs[:, 0]
normals /= np.linalg.norm(normals, axis=1)[:, np.newaxis]

def get_racing_metrics(node_alphas):
    # Periodic Spline Interpolation (True C2 Continuity)
    indices = np.linspace(0, len(centerline), N_NODES, endpoint=False)
    # Adding a wrap point for the Spline engine to recognize periodicity
    cs = CubicSpline(np.append(indices, len(centerline)),
                     np.append(node_alphas, node_alphas[0]), bc_type='periodic')

    full_alphas = cs(np.arange(len(centerline)))
    full_alphas = np.clip(full_alphas, -TRACK_WIDTH/2.1, TRACK_WIDTH/2.1)

    # Path & Curvature
    path = centerline + (full_alphas[:, np.newaxis] * normals)
    path_ext = np.vstack([path, path[:2]]) # Small overlap for gradient stability

    dx = np.gradient(path_ext[:, 0]); dy = np.gradient(path_ext[:, 1])
    ddx = np.gradient(dx); ddy = np.gradient(dy)
    # Numerical Curvature (1/R)
    curvature = np.abs(dx * ddy - dy * ddx) / (dx**2 + dy**2 + 1e-6)**1.5
    curvature = curvature[:-2] # Trim back to original size

    # Multi-Pass Velocity Profile (Removes the Kink)
    ds = np.linalg.norm(np.roll(path, -1, axis=0) - path, axis=1)
    v_limit = np.sqrt(MU * G / (curvature + 1e-6))
    v_prof = np.copy(v_limit)

    # Run passes 3 times to let the boundary condition propagate throughout the loop
    for _ in range(3):
        # Forward Pass (Accel)
        for i in range(len(v_prof)):
            next_idx = (i + 1) % len(v_prof)
            v_prof[next_idx] = min(v_prof[next_idx], np.sqrt(v_prof[i]**2 + 2 * A_MAX * ds[i]))
        # Backward Pass (Braking)
        for i in range(len(v_prof) - 1, -1, -1):
            prev_idx = (i - 1) % len(v_prof)
            v_prof[prev_idx] = min(v_prof[prev_idx], np.sqrt(v_prof[i]**2 + 2 * DECEL_MAX * ds[prev_idx]))

    lap_time = np.sum(ds / (v_prof + 1e-6))
    return lap_time, v_prof, path

def fitness(alphas):
    return get_racing_metrics(alphas)[0]

# Initializing Swarm
pos = np.random.uniform(-TRACK_WIDTH/3, TRACK_WIDTH/3, (N_PARTICLES, N_NODES))
vel = np.zeros_like(pos)
p_best_pos = np.copy(pos)
p_best_val = np.array([fitness(p) for p in pos])
g_best_pos = p_best_pos[np.argmin(p_best_val)]
g_best_val = np.min(p_best_val)

history = []

for _ in range(N_ITERATIONS):
    r1, r2 = np.random.rand(2)
    # Adaptive inertia for better convergence
    w = 0.8 - (_ / N_ITERATIONS) * 0.4
    vel = w * vel + 1.5 * r1 * (p_best_pos - pos) + 2.0 * r2 * (g_best_pos - pos)
    pos = np.clip(pos + vel, -TRACK_WIDTH/2, TRACK_WIDTH/2)

    for i in range(N_PARTICLES):
        score = fitness(pos[i])
        if score < p_best_val[i]:
            p_best_val[i] = score
            p_best_pos[i] = np.copy(pos[i])
            if score < g_best_val:
                g_best_val = score; g_best_pos = np.copy(pos[i])
    history.append(np.copy(g_best_pos))

fig, ax = plt.subplots(figsize=(10, 8))
cax = fig.add_axes([0.92, 0.2, 0.02, 0.6])

def update(frame):
    ax.clear(); cax.clear()
    inner = centerline - (TRACK_WIDTH/2 * normals); outer = centerline + (TRACK_WIDTH/2 * normals)
    ax.plot(inner[:,0], inner[:,1], 'k-', alpha=0.2); ax.plot(outer[:,0], outer[:,1], 'k-', alpha=0.2)
    ax.fill(np.append(inner[:,0], outer[::-1,0]), np.append(inner[:,1], outer[::-1,1]), 'whitesmoke', alpha=0.5)

    time, v_prof, path = get_racing_metrics(history[frame])
    path_plot = np.vstack([path, path[0]])
    v_plot = np.append(v_prof, v_prof[0])

    # Plot as a continuous line to show smooth loop
    ax.plot(path_plot[:,0], path_plot[:,1], color='gray', alpha=0.3, lw=1)
    # Overlay dots for velocity heatmap
    sc = ax.scatter(path_plot[:,0], path_plot[:,1], c=v_plot, cmap='turbo', s=20, zorder=5)

    fig.colorbar(sc, cax=cax, label='Velocity (m/s)')
    ax.set_title(f"Iteration: {frame} | Optimized Lap: {time:.3f}s", fontsize=12)
    ax.axis('equal')

ani = FuncAnimation(fig, update, frames=len(history), interval=40)
plt.close()
HTML(ani.to_html5_video())